### ISSUE TITLE
Implement Clip Merging

### ISSUE THREAD

**Issue by sr229** [sr229/animegrep#1]
According to OP @daniel-Jones  himself:

> the script itself is a hackjob and if I remember correctly
merging the files was never implemented correctly, I remeber having to merge them manually
for the uploads.

So this will remain a open field of research to implement the clip merging via ffmpeg. As much as possible we have to get everything working.

**Comment by Martmists-GH** [comment]
```bash
# change .mp4 based on extension
ls -Q | grep -E "\.mp4" | sed -e "s/^/file /g" > video_files.txt
ffmpeg -f concat -i video_files.txt full_video.mp4
```

`ls -Q` for listing all files with quotes since it's required for ffmpeg to have double quotes
`grep -E "\.mp4"` for grabbing only the video files
`sed -e "s/^/file /g"` prepends `file` to all arguments
the ffmpeg command concatenates all files, but this requires all videos to be of the **same resolution and fps.** ([more details](https://trac.ffmpeg.org/wiki/Concatenate))

**Comment by sr229** [comment]
I don't think resolution is a problem since we can assume a folder of anime series is consistently 4K for example. @martmists

**Comment by sr229** [comment]
Also looks like we can fit that into `merge()`. 

https://github.com/sr229/animegrep/blob/master/animegrep.sh#L145-L160
